// @ts-nocheck
"use client";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NearProvider} from "@repo/near";
import {ThemeProvider} from "@repo/theme";
import {BitteProvider} from "@repo/mintbase";
import {Layout} from "@/components/layout";

const geistSans = localFont({
	src: "../../public/fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "../../public/fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					<BitteProvider>
						<NearProvider>
							<div className="flex flex-col min-h-screen">
								<Layout>
									{children}
								</Layout>
							</div>
						</NearProvider>
					</BitteProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
